# report.py
from __future__ import annotations

from typing import Dict, List, Optional

import pandas as pd


def df_to_html_table(df: pd.DataFrame) -> str:
    # Light formatting; Streamlit uses its own styles, report needs CSS.
    return df.to_html(index=False, border=0, classes="data-table", justify="left")


def build_report_html(
    inputs_summary: Dict[str, str],
    y1_table: pd.DataFrame,
    chart_html_fragments: List[str],
    narrative_text: str,
    title: str = "Distribution Summary Report",
) -> str:
    inputs_rows = "".join(
        f"<tr><th>{k}</th><td>{v}</td></tr>" for k, v in inputs_summary.items()
    )

    charts_block = "".join(
        f"<div class='chart-block'>{frag}</div>" for frag in chart_html_fragments
    )

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>{title}</title>
  <style>
    body {{
      font-family: Arial, sans-serif;
      margin: 24px;
      color: #111;
    }}
    h1 {{ margin: 0 0 8px 0; }}
    h2 {{ margin-top: 28px; }}
    .meta {{
      margin: 10px 0 18px 0;
      font-size: 14px;
      color: #333;
    }}
    table.inputs {{
      border-collapse: collapse;
      width: 100%;
      margin: 10px 0 18px 0;
    }}
    table.inputs th, table.inputs td {{
      border-bottom: 1px solid #ddd;
      padding: 8px 10px;
      text-align: left;
      vertical-align: top;
      font-size: 14px;
    }}
    .data-table {{
      border-collapse: collapse;
      width: 100%;
      margin-top: 10px;
      font-size: 13px;
    }}
    .data-table th {{
      border-bottom: 2px solid #444;
      padding: 8px 10px;
      text-align: left;
      background: #f6f6f6;
    }}
    .data-table td {{
      border-bottom: 1px solid #ddd;
      padding: 7px 10px;
    }}
    .note {{
      font-size: 12px;
      color: #444;
      margin-top: 6px;
    }}
    pre {{
      background: #f6f6f6;
      padding: 12px;
      white-space: pre-wrap;
      border-radius: 6px;
      font-size: 13px;
    }}
    .chart-block {{
      margin: 18px 0 26px 0;
    }}
  </style>
</head>
<body>
  <h1>{title}</h1>
  <div class="meta">Generated by the calculator app.</div>

  <h2>Inputs</h2>
  <table class="inputs">
    {inputs_rows}
  </table>

  <h2>Y1. Summary Table</h2>
  <div class="note">Rows flagged for ±20% period-over-period change are marked in the Flag column.</div>
  {df_to_html_table(y1_table)}

  <h2>Y2. Charts</h2>
  {charts_block}

  <h2>Y3. Verbal Summary</h2>
  <pre>{narrative_text}</pre>
</body>
</html>
"""
    return html
